/**
 * EventAttendeeDTO Mapping and Utilities
 *
 * Handles conversion between Available Students and EventAttendeeDTO objects
 * Provides functions for managing event attendees with proper pricing and attendance tracking
 */

import { EventAttendeeDTO } from 'src/generated/profile-service'

export interface StudentData {
  id?: string
  userId?: string
  firstName?: string
  lastName?: string
  email?: string
  profilePicture?: string
  picture?: string // UserDTO structure uses 'picture' instead of 'profilePicture'
  [key: string]: any
}

export interface AttendeeWithPricing extends EventAttendeeDTO {
  student?: StudentData
  displayName?: string
  profilePicture?: string
}

/**
 * Converts a student to EventAttendeeDTO with default values
 */
export const studentToEventAttendeeDTO = (
  student: StudentData,
  options: {
    expected?: boolean
    attended?: boolean
    customPrice?: number
    hasCustomPricing?: boolean
  } = {}
): EventAttendeeDTO => {
  const attendeeId = student.userId || student.id
  if (!attendeeId) {
    throw new Error('Student must have userId or id')
  }

  return {
    attendeeId,
    expected: options.expected ?? true, // Default to expected
    attended: options.attended ?? false, // Default to not attended
    hasCustomPricing: options.hasCustomPricing ?? false,
    customPrice: options.customPrice
    // id will be generated by backend when saved
  }
}

/**
 * Converts an array of students to EventAttendeeDTO array
 */
export const studentsToEventAttendeeDTOs = (
  students: StudentData[],
  attendeePrices: { [key: string]: number } = {},
  defaultPrice?: number
): EventAttendeeDTO[] => {
  if (!students || !Array.isArray(students)) {
    return []
  }

  return students
    .map(student => {
      const attendeeId = student.userId || student.id
      if (!attendeeId) return null

      const customPrice = attendeePrices[attendeeId]
      const hasCustomPricing = customPrice !== undefined && customPrice !== defaultPrice

      return studentToEventAttendeeDTO(student, {
        expected: true,
        attended: false,
        customPrice: hasCustomPricing ? customPrice : undefined,
        hasCustomPricing
      })
    })
    .filter(Boolean) as EventAttendeeDTO[]
}

/**
 * Converts EventAttendeeDTO back to student selection format
 */
export const eventAttendeeDTOsToStudentIds = (attendees: EventAttendeeDTO[]): string[] => {
  if (!attendees || !Array.isArray(attendees)) {
    return []
  }

  return attendees
    .filter(attendee => attendee.expected === true)
    .map(attendee => attendee.attendeeId)
    .filter(Boolean) as string[]
}

/**
 * Extracts pricing information from EventAttendeeDTO array
 */
export const extractAttendeePrices = (attendees: EventAttendeeDTO[]): { [key: string]: number } => {
  const prices: { [key: string]: number } = {}

  if (!attendees || !Array.isArray(attendees)) {
    return prices
  }

  attendees.forEach(attendee => {
    if (attendee.attendeeId && attendee.hasCustomPricing && attendee.customPrice !== undefined) {
      prices[attendee.attendeeId] = attendee.customPrice
    }
  })

  return prices
}

/**
 * Merges students data with EventAttendeeDTO to create enriched attendee objects
 */
export const enrichAttendeesWithStudentData = (
  attendees: EventAttendeeDTO[],
  students: StudentData[]
): AttendeeWithPricing[] => {
  // Add null safety check
  if (!attendees || !Array.isArray(attendees)) {
    return []
  }

  return attendees.map(attendee => {
    const student = students.find(s => (s.userId || s.id) === attendee.attendeeId)

    return {
      ...attendee,
      student,
      displayName: student ? `${student.firstName} ${student.lastName}`.trim() : 'Unknown Student',
      // Handle both old structure (UserDTO.picture) and new structure (profilePicture)
      profilePicture: student?.profilePicture || student?.picture
    }
  })
}

/**
 * Updates an attendee's pricing information
 */
export const updateAttendeePrice = (
  attendees: EventAttendeeDTO[],
  attendeeId: string,
  newPrice: number,
  defaultPrice?: number
): EventAttendeeDTO[] => {
  if (!attendees || !Array.isArray(attendees)) {
    return []
  }

  return attendees.map(attendee => {
    if (attendee.attendeeId === attendeeId) {
      const hasCustomPricing = newPrice !== defaultPrice
      return {
        ...attendee,
        customPrice: hasCustomPricing ? newPrice : undefined,
        hasCustomPricing
      }
    }
    return attendee
  })
}

/**
 * Marks an attendee as attended/not attended
 */
export const updateAttendanceStatus = (
  attendees: EventAttendeeDTO[],
  attendeeId: string,
  attended: boolean
): EventAttendeeDTO[] => {
  if (!attendees || !Array.isArray(attendees)) {
    return []
  }

  return attendees.map(attendee => (attendee.attendeeId === attendeeId ? { ...attendee, attended } : attendee))
}

/**
 * Adds a new attendee to the list
 */
export const addAttendee = (
  attendees: EventAttendeeDTO[],
  student: StudentData,
  options: {
    expected?: boolean
    customPrice?: number
    defaultPrice?: number
  } = {}
): EventAttendeeDTO[] => {
  if (!attendees || !Array.isArray(attendees)) {
    attendees = []
  }

  const attendeeId = student.userId || student.id
  if (!attendeeId) {
    throw new Error('Student must have userId or id')
  }

  // Check if attendee already exists
  if (attendees.some(a => a.attendeeId === attendeeId)) {
    return attendees
  }

  const newAttendee = studentToEventAttendeeDTO(student, {
    expected: options.expected ?? true,
    customPrice: options.customPrice,
    hasCustomPricing: options.customPrice !== undefined && options.customPrice !== options.defaultPrice
  })

  return [...attendees, newAttendee]
}

/**
 * Removes an attendee from the list
 */
export const removeAttendee = (attendees: EventAttendeeDTO[], attendeeId: string): EventAttendeeDTO[] => {
  if (!attendees || !Array.isArray(attendees)) {
    return []
  }

  return attendees.filter(attendee => attendee.attendeeId !== attendeeId)
}

/**
 * Validates EventAttendeeDTO array
 */
export const validateEventAttendees = (
  attendees: EventAttendeeDTO[]
): {
  isValid: boolean
  errors: string[]
} => {
  const errors: string[] = []

  if (!attendees || !Array.isArray(attendees)) {
    return { isValid: true, errors: [] }
  }

  attendees.forEach((attendee, index) => {
    if (!attendee.attendeeId) {
      errors.push(`Attendee at index ${index} missing attendeeId`)
    }

    if (attendee.hasCustomPricing && attendee.customPrice === undefined) {
      errors.push(`Attendee ${attendee.attendeeId} has custom pricing but no price set`)
    }

    if (attendee.customPrice !== undefined && attendee.customPrice < 0) {
      errors.push(`Attendee ${attendee.attendeeId} has negative price`)
    }
  })

  return {
    isValid: errors.length === 0,
    errors
  }
}

/**
 * Gets attendees filtered by expected status
 */
export const getExpectedAttendees = (attendees: EventAttendeeDTO[]): EventAttendeeDTO[] => {
  if (!attendees || !Array.isArray(attendees)) {
    return []
  }
  return attendees.filter(attendee => attendee.expected === true)
}

/**
 * Gets attendees filtered by attendance status
 */
export const getAttendedAttendees = (attendees: EventAttendeeDTO[]): EventAttendeeDTO[] => {
  if (!attendees || !Array.isArray(attendees)) {
    return []
  }
  return attendees.filter(attendee => attendee.attended === true)
}

/**
 * Gets total expected count
 */
export const getExpectedCount = (attendees: EventAttendeeDTO[]): number => {
  return getExpectedAttendees(attendees).length
}

/**
 * Gets total attended count
 */
export const getAttendedCount = (attendees: EventAttendeeDTO[]): number => {
  return getAttendedAttendees(attendees).length
}

/**
 * Calculates total revenue from attendees
 */
export const calculateTotalRevenue = (
  attendees: EventAttendeeDTO[],
  defaultPrice: number = 0,
  onlyAttended: boolean = false
): number => {
  if (!attendees || !Array.isArray(attendees)) {
    return 0
  }

  const relevantAttendees = onlyAttended ? getAttendedAttendees(attendees) : getExpectedAttendees(attendees)

  return relevantAttendees.reduce((total, attendee) => {
    const price = attendee.hasCustomPricing && attendee.customPrice !== undefined ? attendee.customPrice : defaultPrice
    return total + price
  }, 0)
}
